import { MigrationInterface, QueryRunner } from "typeorm";

export class AddKeywordTables1767263046784 implements MigrationInterface {
    name = 'AddKeywordTables1767263046784'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ranking_histories" DROP CONSTRAINT "ranking_histories_place_keyword_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "place_keywords" DROP CONSTRAINT "place_keywords_keyword_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "place_keywords" DROP CONSTRAINT "place_keywords_place_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "reviews_place_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "review_histories" DROP CONSTRAINT "review_histories_place_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "competitor_snapshots" DROP CONSTRAINT "competitor_snapshots_competitor_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "competitors" DROP CONSTRAINT "competitors_place_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "notification_logs" DROP CONSTRAINT "notification_logs_place_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "notification_logs" DROP CONSTRAINT "notification_logs_notification_setting_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "notification_settings" DROP CONSTRAINT "notification_settings_place_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "notification_settings" DROP CONSTRAINT "notification_settings_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "places" DROP CONSTRAINT "places_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "place_keywords" DROP CONSTRAINT "place_keywords_place_id_keyword_id_region_key"`);
        await queryRunner.query(`ALTER TABLE "competitors" DROP CONSTRAINT "competitors_place_id_competitor_naver_place_id_key"`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token" character varying(500) NOT NULL, "expires_at" TIMESTAMP NOT NULL, "is_revoked" boolean NOT NULL DEFAULT false, "device_info" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "revoked_at" TIMESTAMP, "user_id" uuid NOT NULL, CONSTRAINT "UQ_4542dd2f38a61354a040ba9fd57" UNIQUE ("token"), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_refresh_tokens_token" ON "refresh_tokens" ("token") `);
        await queryRunner.query(`CREATE INDEX "idx_refresh_tokens_user_id" ON "refresh_tokens" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "keywords" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."idx_ranking_histories_place_keyword_checked"`);
        await queryRunner.query(`ALTER TABLE "ranking_histories" ALTER COLUMN "checked_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "ranking_histories" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking_histories" ALTER COLUMN "place_keyword_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "place_keywords" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "place_keywords" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "place_keywords" ALTER COLUMN "place_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "place_keywords" ALTER COLUMN "keyword_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reviews" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reviews" ALTER COLUMN "place_id" DROP NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."idx_review_histories_place_checked"`);
        await queryRunner.query(`ALTER TABLE "review_histories" ALTER COLUMN "blog_review_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "review_histories" ALTER COLUMN "visitor_review_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "review_histories" ALTER COLUMN "checked_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "review_histories" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "review_histories" ALTER COLUMN "place_id" DROP NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."idx_competitor_snapshots_competitor_checked"`);
        await queryRunner.query(`ALTER TABLE "competitor_snapshots" ALTER COLUMN "checked_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "competitor_snapshots" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competitor_snapshots" ALTER COLUMN "competitor_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competitors" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competitors" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competitors" ALTER COLUMN "place_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_logs" ALTER COLUMN "is_sent" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_logs" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_logs" ALTER COLUMN "notification_setting_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_logs" ALTER COLUMN "place_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_settings" ALTER COLUMN "is_enabled" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_settings" DROP COLUMN "conditions"`);
        await queryRunner.query(`ALTER TABLE "notification_settings" ADD "conditions" text`);
        await queryRunner.query(`ALTER TABLE "notification_settings" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_settings" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_settings" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "places" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "places" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "places" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "places" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_ranking_histories_place_keyword_checked" ON "ranking_histories" ("place_keyword_id", "checked_at") `);
        await queryRunner.query(`CREATE INDEX "idx_review_histories_place_checked" ON "review_histories" ("place_id", "checked_at") `);
        await queryRunner.query(`CREATE INDEX "idx_competitor_snapshots_competitor_checked" ON "competitor_snapshots" ("competitor_id", "checked_at") `);
        await queryRunner.query(`ALTER TABLE "place_keywords" ADD CONSTRAINT "UQ_c280ece277c5eefe65790a0dfab" UNIQUE ("place_id", "keyword_id", "region")`);
        await queryRunner.query(`ALTER TABLE "competitors" ADD CONSTRAINT "UQ_bad51ba9b294b2462e8e361996c" UNIQUE ("place_id", "competitor_naver_place_id")`);
        await queryRunner.query(`ALTER TABLE "ranking_histories" ADD CONSTRAINT "FK_541f214694da6edab729b5917dd" FOREIGN KEY ("place_keyword_id") REFERENCES "place_keywords"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "place_keywords" ADD CONSTRAINT "FK_1be2f9e0574d688f88c9ec03c8d" FOREIGN KEY ("place_id") REFERENCES "places"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "place_keywords" ADD CONSTRAINT "FK_0fd6604ac0995bc6d0d07ffe379" FOREIGN KEY ("keyword_id") REFERENCES "keywords"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_d2616b72cb3787ad20b88a3aa67" FOREIGN KEY ("place_id") REFERENCES "places"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review_histories" ADD CONSTRAINT "FK_db60d1424d0a3ad078b113510ab" FOREIGN KEY ("place_id") REFERENCES "places"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competitor_snapshots" ADD CONSTRAINT "FK_7c1461ed7dfc5dba78bbb87f29e" FOREIGN KEY ("competitor_id") REFERENCES "competitors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competitors" ADD CONSTRAINT "FK_6cdeb6f0a99142483bdb1e5961e" FOREIGN KEY ("place_id") REFERENCES "places"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_logs" ADD CONSTRAINT "FK_96b49c9f158f11cb9dfdeccc847" FOREIGN KEY ("notification_setting_id") REFERENCES "notification_settings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_logs" ADD CONSTRAINT "FK_fedc1fb9bf0b9e486d6fa1c6429" FOREIGN KEY ("place_id") REFERENCES "places"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_settings" ADD CONSTRAINT "FK_91a7ffebe8b406c4470845d4781" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_settings" ADD CONSTRAINT "FK_533d48d7a72e61bc10fd17356f2" FOREIGN KEY ("place_id") REFERENCES "places"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "places" ADD CONSTRAINT "FK_24094a8af93e0d76e84e563b6ed" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "places" DROP CONSTRAINT "FK_24094a8af93e0d76e84e563b6ed"`);
        await queryRunner.query(`ALTER TABLE "notification_settings" DROP CONSTRAINT "FK_533d48d7a72e61bc10fd17356f2"`);
        await queryRunner.query(`ALTER TABLE "notification_settings" DROP CONSTRAINT "FK_91a7ffebe8b406c4470845d4781"`);
        await queryRunner.query(`ALTER TABLE "notification_logs" DROP CONSTRAINT "FK_fedc1fb9bf0b9e486d6fa1c6429"`);
        await queryRunner.query(`ALTER TABLE "notification_logs" DROP CONSTRAINT "FK_96b49c9f158f11cb9dfdeccc847"`);
        await queryRunner.query(`ALTER TABLE "competitors" DROP CONSTRAINT "FK_6cdeb6f0a99142483bdb1e5961e"`);
        await queryRunner.query(`ALTER TABLE "competitor_snapshots" DROP CONSTRAINT "FK_7c1461ed7dfc5dba78bbb87f29e"`);
        await queryRunner.query(`ALTER TABLE "review_histories" DROP CONSTRAINT "FK_db60d1424d0a3ad078b113510ab"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_d2616b72cb3787ad20b88a3aa67"`);
        await queryRunner.query(`ALTER TABLE "place_keywords" DROP CONSTRAINT "FK_0fd6604ac0995bc6d0d07ffe379"`);
        await queryRunner.query(`ALTER TABLE "place_keywords" DROP CONSTRAINT "FK_1be2f9e0574d688f88c9ec03c8d"`);
        await queryRunner.query(`ALTER TABLE "ranking_histories" DROP CONSTRAINT "FK_541f214694da6edab729b5917dd"`);
        await queryRunner.query(`ALTER TABLE "competitors" DROP CONSTRAINT "UQ_bad51ba9b294b2462e8e361996c"`);
        await queryRunner.query(`ALTER TABLE "place_keywords" DROP CONSTRAINT "UQ_c280ece277c5eefe65790a0dfab"`);
        await queryRunner.query(`DROP INDEX "public"."idx_competitor_snapshots_competitor_checked"`);
        await queryRunner.query(`DROP INDEX "public"."idx_review_histories_place_checked"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ranking_histories_place_keyword_checked"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "places" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "places" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "places" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "places" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_settings" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_settings" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_settings" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_settings" DROP COLUMN "conditions"`);
        await queryRunner.query(`ALTER TABLE "notification_settings" ADD "conditions" jsonb`);
        await queryRunner.query(`ALTER TABLE "notification_settings" ALTER COLUMN "is_enabled" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_logs" ALTER COLUMN "place_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_logs" ALTER COLUMN "notification_setting_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_logs" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_logs" ALTER COLUMN "is_sent" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competitors" ALTER COLUMN "place_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competitors" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competitors" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competitor_snapshots" ALTER COLUMN "competitor_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competitor_snapshots" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "competitor_snapshots" ALTER COLUMN "checked_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "idx_competitor_snapshots_competitor_checked" ON "competitor_snapshots" ("checked_at", "competitor_id") `);
        await queryRunner.query(`ALTER TABLE "review_histories" ALTER COLUMN "place_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "review_histories" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "review_histories" ALTER COLUMN "checked_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "review_histories" ALTER COLUMN "visitor_review_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "review_histories" ALTER COLUMN "blog_review_count" DROP NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_review_histories_place_checked" ON "review_histories" ("checked_at", "place_id") `);
        await queryRunner.query(`ALTER TABLE "reviews" ALTER COLUMN "place_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reviews" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "place_keywords" ALTER COLUMN "keyword_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "place_keywords" ALTER COLUMN "place_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "place_keywords" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "place_keywords" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking_histories" ALTER COLUMN "place_keyword_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking_histories" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking_histories" ALTER COLUMN "checked_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "idx_ranking_histories_place_keyword_checked" ON "ranking_histories" ("checked_at", "place_keyword_id") `);
        await queryRunner.query(`ALTER TABLE "keywords" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."idx_refresh_tokens_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_refresh_tokens_token"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`ALTER TABLE "competitors" ADD CONSTRAINT "competitors_place_id_competitor_naver_place_id_key" UNIQUE ("place_id", "competitor_naver_place_id")`);
        await queryRunner.query(`ALTER TABLE "place_keywords" ADD CONSTRAINT "place_keywords_place_id_keyword_id_region_key" UNIQUE ("place_id", "keyword_id", "region")`);
        await queryRunner.query(`ALTER TABLE "places" ADD CONSTRAINT "places_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_settings" ADD CONSTRAINT "notification_settings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_settings" ADD CONSTRAINT "notification_settings_place_id_fkey" FOREIGN KEY ("place_id") REFERENCES "places"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_logs" ADD CONSTRAINT "notification_logs_notification_setting_id_fkey" FOREIGN KEY ("notification_setting_id") REFERENCES "notification_settings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_logs" ADD CONSTRAINT "notification_logs_place_id_fkey" FOREIGN KEY ("place_id") REFERENCES "places"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competitors" ADD CONSTRAINT "competitors_place_id_fkey" FOREIGN KEY ("place_id") REFERENCES "places"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competitor_snapshots" ADD CONSTRAINT "competitor_snapshots_competitor_id_fkey" FOREIGN KEY ("competitor_id") REFERENCES "competitors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review_histories" ADD CONSTRAINT "review_histories_place_id_fkey" FOREIGN KEY ("place_id") REFERENCES "places"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "reviews_place_id_fkey" FOREIGN KEY ("place_id") REFERENCES "places"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "place_keywords" ADD CONSTRAINT "place_keywords_place_id_fkey" FOREIGN KEY ("place_id") REFERENCES "places"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "place_keywords" ADD CONSTRAINT "place_keywords_keyword_id_fkey" FOREIGN KEY ("keyword_id") REFERENCES "keywords"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ranking_histories" ADD CONSTRAINT "ranking_histories_place_keyword_id_fkey" FOREIGN KEY ("place_keyword_id") REFERENCES "place_keywords"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
